<?
$PERM["lk-pokupatelya"]["8"]="W";
$PERM["lk-pokupatelya"]["6"]="R";
$PERM["lk-pokupatelya"]["7"]="X";
$PERM["lk-pokupatelya"]["*"]="D";
$PERM["lk-prodavtsa"]["8"]="W";
$PERM["lk-prodavtsa"]["7"]="R";
$PERM["lk-prodavtsa"]["*"]="D";
$PERM["index_inc.php"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["5"]="W";
$PERM["obyavleniya"]["8"]="W";
$PERM["o-servise"]["8"]="W";
$PERM["bitrix"]["8"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["/"]["*"]="R";
?>